### ISSUE TITLE
Update to latest Node to get rid of deprecation warnings

### ISSUE THREAD

**Issue by Piedone** [cezarypiatek/VsixPublisherAction#2]
When you run the action, you get the following warning:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: cezarypiatek/VsixPublisherAction@759bd2ec02ac1b13dea56d8c84834e517278b5b1

Please update the Node version to latest (LTS) to get rid of this.

**Comment by cezarypiatek** [comment]
Any PR is welcomed ;)

**Comment by cezarypiatek** [comment]
Fixed

**Comment by Piedone** [comment]
Thank you!
